### PR TITLE
Fix: Resolve fuel code increment and row duplication order issue - #1303

### LINKED ISSUE #1303: LCFS - Fuel code number
**Description:**  
Currently, the functionality for assigning a new fuel code number works well when the form is loaded using the "New fuel code" button. The same functionality should be extended to when a user clicks the "Add row" and "Duplicate row" buttons. 

**Wireframe:**  
N/A (or attach a relevant wireframe if available).

**Purpose and benefit to user:**  
This update ensures consistency in the behavior of the application across different entry points, reducing user confusion and enhancing the user experience by automating the assignment of new fuel codes in all relevant scenarios.

**Acceptance Criteria:**  
- [ ] When a user clicks the "Add row" button, the form should assign the next available fuel code number based on default prefix and updated if the prefix is updated from the dropdown list
- [ ] When a user clicks the "Duplicate row" icon, the form should assign the next available fuel code number based on prefix that was duplicated and updated if the prefix is updated from the dropdown list
- [ ] The process for assigning the fuel code number should mirror the existing functionality when using the "New fuel code" button.  

**Development Checklist:**  
- [ ] Apply the same function (as New Fuel Code button action) to trigger when the "Add row" button is clicked based on default prefix (BCLCF) to insert next fuel code number.
- [ ] Apply the same function (as New Fuel Code button action) to trigger when the "Duplicate row" icon is clicked based on default prefix (BCLCF) to insert next fuel code number.
- [ ] Apply the same function (as New Fuel Code button action) to trigger when the user changes the Prefix selection.

**Notes:**

### PR DESCRIPTION
**Pull request by hamed-valiollahi**
This PR fixes the issue where the fuel code number does not increment after using the duplicate row function and ensures the duplicated row is placed below the existing record, caused by a conflict with #1446.

Closes #1303

### CODE REVIEW

**Review by AlexZorkin — CHANGES_REQUESTED** [review]
How can we add a test to cover this duplication order?

**Comment by hamed-valiollahi** [comment]
@AlexZorkin Thank you for the code review! Do you think it would be a good idea to cover this with e2e tests? If so, should I create a new ticket for it?

**Comment by AlexZorkin** [comment]
Sure I will create a followup ticket.

**Review by AlexZorkin — APPROVED** [review]

**Comment by hamed-valiollahi** [comment]
Thank you, Alex!

**Pull request merged**
