### PR TITLE
Feat: Add User Activity Table for BCeID and IDIR Users - 177, 189

### LINKED ISSUE #177: LCFS - User Activity table for BCeID users
**Description**:
As a BCeID LCFS User, I want to view a table of major user activities on the View User page, so that I can monitor significant actions taken by the user within the LCFS system.

**Wireframe:** 
Image

**Purpose and benefit to user:**
This is an important audit feature that exists in TFRS and should be retained in LCFS. TFRS can be reviewed for how to duplicate the functionality.

**Acceptance Criteria**:

Only major transactions (Signing, Submitting, Sending) should be displayed in the table; minor transactions such as saving drafts should be excluded.

Populate the "User Activity" table on the View User page with the following details:

- Action taken: Show the specific action taken (e.g., Signing, Submitting, Sending).
- Transaction type: Display the type of transaction taken.
- Transaction ID: Display the transaction number associated with the action.
- Timestamp : Display the date/timestamp of when the action occurred.
- Organization: this column should be removed

The table row should act as a clickable link to the specific record.

**Notes:**
This "User Activity" table is also available to IDIR users under the "Organization" tab.

Image

### LINKED ISSUE #189: LCFS - User Activity table for IDIR users
**Description**:
As a IDIR LCFS User, I want to view a table of major user activities on the View User page, so that I can monitor significant actions taken by the user within the LCFS system.

**Screenshot 1 Individual User:** 
Image

**Screenshot 2 All users:** 
Image

**Purpose and benefit to user:**
This is an important audit feature that exists in TFRS and should be retained in LCFS. TFRS can be reviewed for how to duplicate the functionality.

**Acceptance Criteria**:

Only major transactions (Recommended, Recorded, Refused, Approved, Declined) should be displayed in the table; minor transactions such as saving drafts or comments should be excluded.

Populate the "User Activity" table on the View User page with the following details:

- Action taken: Show the specific action taken (e.g., Recommended, Recorded, Refused, Approved, Declined).
- Transaction type: Display the type of transaction taken.
- Transaction ID: Display the transaction number associated with the action.
- Timestamp : Display the date/timestamp of when the action occurred.
- Organization: this column should be removed

The table row should act as a clickable link to the specific record.

### PR DESCRIPTION
**Pull request by hamed-valiollahi**
This PR adds the user activity table for both BCeID and IDIR users on the View User page.

It also includes improvements such as:
- Added admin adjustment history records on the 'dev' environment.
- Fixed validation error message for quantity and agreement date in the New Transfer page.

Closes #177
Closes #189

### CODE REVIEW

**Review by AlexZorkin — COMMENTED** [review]
Feature tested well. Code looks good, but please add frontend and backend tests to cover this new feature. Also do you have any thoughts on how this will perform when there are 10000s or more history records in the system? Specifically when building the full activity list for all users?

**Review by AlexZorkin — CHANGES_REQUESTED** [review]
Once tests are included this feature is good to go.

**Comment by hamed-valiollahi** [comment]
Thanks, Alex, for your feedback. I’ve added the note we discussed earlier, along with both front-end and back-end tests.

**Review by AlexZorkin — APPROVED** [review]
Thanks for adding the tests 👍

**Pull request merged**
