### PR TITLE
Feat: Add Auto-Generation for FSE Registration Numbers - 715, 744

### LINKED ISSUE #715: LCFS - FSE, auto-generation of Registration number
**Description:**

Card #744 must be done first to implement Organization ID.

Implement functionality to generate a unique registration number upon saving a new FSE based on the following logic:

- Organization ID: Current Organization ID, 4 character alphanumeric ID from the org table
- Postal code: Last 3 characters of PC entered of FSE
- Sequential number: 001-999, this number will reset to 001 for each different postal code change. If the number has existed previously then increment to the next number.
- example: 0055-0B9-001

**Wireframe:** <link>
https://preview.uxpin.com/da68049c0af15edd7ce4e47e4bee431fed40c30d#/pages/178596806

**Purpose and benefit to user:** Each FSE will have a unique registration number as outlined in the legislation.

**Acceptance Criteria:**

- [ ] As a BCeID user with Compliance reporting role, when I am saving a new FSE row, then the system generates a unique registration number based on the Organization ID, Postal code, and a sequential number.

**Development Checklist:**

- [ ] A  Ensure the system retrieves the current Organization ID from the org table.
- [ ] B  Extract the last 3 characters of the Postal Code entered for the FSE.
- [ ] C  Implement logic to generate a sequential number (001-999) that resets with each different Postal Code.
- [ ] D  Check the existing registration numbers to determine the next available sequential number for the given Postal Code.
- [ ] E  Concatenate the formatted Supplier ID, last 3 characters of the Postal Code, and the sequential number to form the unique registration number.
- [ ] F  Check the newly generated ID against existing registration numbers to determine the ID has never been used before. If it has try the next sequential number (001-999).
- [ ] G  Validate the uniqueness of the registration number before saving the FSE row.
- [ ] H  Handle any potential edge cases, such as missing or improperly formatted Postal Codes.
- [ ] I  Update the database schema if necessary to store the unique registration numbers.
- [ ] J  Test the generation and validation of registration numbers thoroughly, including edge cases.
- [ ] K  Ensure the process is seamless and does not introduce any significant delays in saving the FSE row.

**Notes:**

### PR DESCRIPTION
**Pull request by hamed-valiollahi**
This PR adds the functionality to auto-generate unique registration numbers for FSEs using Organization ID, Postal Code, and a sequential number.

Closes #715 #744

### CODE REVIEW

**Review by kevin-hashimoto — CHANGES_REQUESTED** [review]
The registration number generation is working well when tested! 👍🏻

I think we may be missing a couple things from #744. To my understanding it seems like we dont want to expose the primary org ID key. We may need to generate a another unique 4 digit alphanum ID to obfuscate the primary org ID.

We will also need the logic to generate this ID when a new org is created and adjustments to the Org model and seeder to reflect this change

**Comment by hamed-valiollahi** [comment]
> The registration number generation is working well when tested! 👍🏻
> 
> I think we may be missing a couple things from #744. To my understanding it seems like we dont want to expose the primary org ID key. We may need to generate a another unique 4 digit alphanum ID to obfuscate the primary org ID.
> 
> We will also need the logic to generate this ID when a new org is created and adjustments to the Org model and seeder to reflect this change

@kevin-hashimoto Thank you for reviewing my PR, Kevin! Good catch! You're right, I missed that part of the ticket. I'll make the changes. 👍

**Review by kevin-hashimoto — APPROVED** [review]

**Comment by hamed-valiollahi** [comment]
@kevin-hashimoto Could you please review my PR again? The changes are:

- Use the full postal code in FSE registration code as requested.
- Resolved the issue of generating the FSE registration code based on both the organization code and the postal code instead of just the postal code.

Thank you!

**Review by kevin-hashimoto — APPROVED** [review]

**Review by AlexZorkin — APPROVED** [review]
Looks great :)

**Pull request merged**
