### PR TITLE
Add number formatter to Nameplace Capacity

### PR DESCRIPTION
**Pull request by dhaselhan**

### CODE REVIEW

**Review by prv-proton — APPROVED** [review]
👍

**Review by prv-proton — CHANGES_REQUESTED** [review]
commas won't gets added while editing, get formatted after editing is complete.

**Comment by dhaselhan** [comment]
> Hi @dhaselhan , thanks for the implementation, Please find my observations below.
> 
> * commas won't get added while editing, instead it gets formatted after editing is complete.
> 
> image image
> * Using NumberEditor component should fix this issue. Also if possible please fix the alignment to be same while editing and not editing.

Good catch Prashanth! Updated the code to use the NumberEditor and it works great. I did look at other places for column alignment and it looks like Fuel Quantity follows the same left/right behavior and I couldn't find any cells that work the way you are suggesting.

**Comment by prv-proton** [comment]
> > Hi @dhaselhan , thanks for the implementation, Please find my observations below.
> > 
> > * commas won't get added while editing, instead it gets formatted after editing is complete.
> > 
> > image image
> > 
> > * Using NumberEditor component should fix this issue. Also if possible please fix the alignment to be same while editing and not editing.
> 
> Good catch Prashanth! Updated the code to use the NumberEditor and it works great. I did look at other places for column alignment and it looks like Fuel Quantity follows the same left/right behavior and I couldn't find any cells that work the way you are suggesting.

I had a ticket similar to this changes in FuelCode carbonIntensity, and Al suggested this change. you can refer here
frontend/src/views/FuelCodes/AddFuelCode/_schema.jsx
`type: 'leftAligned'`. We can confirm this with Al and Stuart tomorrow if these needs to be consistent across. Thanks for the changes, everything looks good.

**Review by prv-proton — APPROVED** [review]

**Pull request merged**
