### PR TITLE
fix: Sorting & Display of FSE

### PR DESCRIPTION
**Pull request by dhaselhan**
* Sort both paginated and non paginated by create date asc to match other schedules
* Fix kWH usage column to use nice number formatter without decimals

### CODE REVIEW

**Review by hamed-valiollahi — APPROVED** [review]
Looks good to me!

As a suggestion, would sorting by `id` be more efficient here since integer comparisons are typically faster than timestamp comparisons like `created_at`?

**Comment by dhaselhan** [comment]
> Looks good to me!
> 
> As a suggestion, would sorting by `id` be more efficient here since integer comparisons are typically faster than timestamp comparisons like `created_date`?

Depending on how ETL works this may or may not be true. ETL may insert records with a higher ID but a copied Create Date from TFRS. Ill ask Alex.

**Comment by hamed-valiollahi** [comment]
> > Looks good to me!
> > As a suggestion, would sorting by `id` be more efficient here since integer comparisons are typically faster than timestamp comparisons like `created_date`?
> 
> Depending on how ETL works this may or may not be true. ETL may insert records with a higher ID but a copied Create Date from TFRS. Ill ask Alex.

Thank you! In case there is significant improvement, we can also update the ETL to ensure the correct order of fetching data. Also, I noticed that there are a few places in the database where the tables don’t have proper indexing. It would be great if we could check and address that as well.

**Comment by dhaselhan** [comment]
> > > Looks good to me!
> > > As a suggestion, would sorting by `id` be more efficient here since integer comparisons are typically faster than timestamp comparisons like `created_date`?
> > 
> > 
> > Depending on how ETL works this may or may not be true. ETL may insert records with a higher ID but a copied Create Date from TFRS. Ill ask Alex.
> 
> Thank you! In case there is significant improvement, we can also update the ETL to ensure the correct order of fetching data. Also, I noticed that there are a few places in the database where the tables don’t have proper indexing. It would be great if we could check and address that as well.

Talked to Alex, he mentioned we are transferring Create Date so we can use that.

**Comment by hamed-valiollahi** [comment]
Nice, thanks, Daniel!

**Pull request merged**
