### PR TITLE
feat: unit tests for AddEditViewTransfer

### PR DESCRIPTION
**Pull request by kevin-hashimoto**
- feat: vitest unit tests for the `AddEditViewTransfer` component

### CODE REVIEW

**Comment by kevin-hashimoto** [comment]
Having trouble creating spys for mutations and state changes

**Comment by AlexZorkin** [comment]
What's the plan with this pr?

**Comment by kevin-hashimoto** [comment]
@prv-proton - were you still working on this? I can take another stab at this if your not

**Comment by prv-proton** [comment]
@kevin-hashimoto , is this ready for review?

**Comment by kevin-hashimoto** [comment]
@prv-proton yes ready for review

**Pull request merged**
