### PR TITLE
Feat: Analyst recommend to director 256

### PR DESCRIPTION
**Pull request by kevin-hashimoto**
#256 

- feat:  recommendation component that houses the recommend options for an analyst
- feat:  transfer_recommendation_status table for the analyst recommendation status
- feat: seeder for transfer recommendation status
- feat: button cluster for the submitted status transfer

### CODE REVIEW

**Review by AlexZorkin — COMMENTED** [review]
What's the benefit of user the transfer_recommendation_status over just setting the transfer status to either Recorded or Refused?

**Comment by kevin-hashimoto** [comment]
> What's the benefit of user the transfer_recommendation_status over just setting the transfer status to either Recorded or Refused?

My thinking was that since the recommendation of 'refuse' or 'record' was not really a transfer status, but more of a sub status of 'recommended' I opted to keep that separate. It does however create a bit of overhead managing another table but I think that overhead is quite small. Thinking of it now, we could just create another column that takes a recommendation enum ( 'refuse', 'record' ). thoughts?

**Comment by AlexZorkin** [comment]
I like your idea of creating a new enum column on Transfer that holds the recommendation value. Eliminates the need for a join every time we call Transfer.

**Review by AlexZorkin — CHANGES_REQUESTED** [review]
I like your idea of creating a new enum column on Transfer that holds the recommendation value. Eliminates the need for a join every time we call Transfer. Please go ahead with that change and fix any conflicts. Thanks :)

**Review by AlexZorkin — APPROVED** [review]
This is great. Thank you for changing up the recommendation.

**Pull request merged**
