### PR TITLE
Fix: Update Fuel Select Activation Color - 1429

### LINKED ISSUE #1429: LCFS - Schedules, Fuel code validation
**Description:**  
For the 4 schedules input forms:
1. Fuel supply
2. Export fuel
3. Allocation agreement
4. Other use

If the option 'Fuel code - section 19 (b) (i)' is selected under 'Determining carbon intensity', the 'Fuel code' cell must become mandatory. It should not pass validation or allow saving until a valid fuel code is selected. If only one fuel code exists, it should auto-populate. If multiple fuel codes exist, no default value should be set; the user must explicitly select one.

**Wireframe:**  
Not applicable.

**Purpose and benefit to user:**  
This ensures accurate and complete data entry for determining carbon intensity, reducing errors and enhancing compliance with validation rules.

**Acceptance Criteria:**  
- [ ] When 'Fuel code - section 19 (b) (i)' is selected in the 'Determining carbon intensity' dropdown:
  - [ ] The 'Fuel code' cell becomes mandatory.
  - [ ] Saving the form without selecting a 'Fuel code' triggers a validation error.
- [ ] If only one fuel code exists:
  - [ ] The 'Fuel code' cell auto-populates with that code.
- [ ] If multiple fuel codes exist:
  - [ ] No default fuel code is pre-selected.
  - [ ] The user is required to manually select a fuel code before saving.

**Development Checklist:**  
- [ ] Implement logic to make the 'Fuel code' cell mandatory when 'Fuel code - section 19 (b) (i)' is selected.
- [ ] Configure auto-population of 'Fuel code' when only one option exists.
- [ ] Prevent auto-selection when multiple fuel codes are available; enforce manual selection.
- [ ] Add validation error messaging for unselected mandatory 'Fuel code'.
- [ ] Apply these rules to all 4 schedules: Fuel supply, Export fuel, Allocation agreement, and Other use input forms.
- [ ] Test scenarios with single and multiple fuel codes to ensure correct behavior.

**Notes:**  
- Confirm the list of fuel codes and their availability across different schedules.
- Ensure error messages are user-friendly and clearly indicate the requirement to select a 'Fuel code'.

### PR DESCRIPTION
**Pull request by hamed-valiollahi**
This PR ensures the Fuel select component turns white when activated.

Closes #1429

### CODE REVIEW

**Review by AlexZorkin — CHANGES_REQUESTED** [review]
This updates the styling, but is the field actually required in validation? I would like to see the conditional validation and then tests to cover that scenario.

**Comment by hamed-valiollahi** [comment]
@AlexZorkin Thank you for the code review! This PR is a fix to my [previous PR](https://github.com/bcgov/lcfs/pull/1461). I have implemented a conditional check based on whether the 'Fuel code - section 19 (b) (i)' option is selected in all four schedules. Please review the PR for more details and let me know if any changes are required.

I'll add the required tests as well. Thanks for pointing this out!

**Comment by hamed-valiollahi** [comment]
@AlexZorkin For this one, I think we could also consider writing E2E tests. Do you think that would be a good idea?

**Comment by AlexZorkin** [comment]
ok thanks for the clarification. I don't think we need an end to end test on this specifically. I think this is good to go 👍

**Review by AlexZorkin — APPROVED** [review]

**Comment by hamed-valiollahi** [comment]
Sure, thanks, Alex!

**Pull request merged**
