### PR TITLE
Feat: Update 'Other' option text in dropdown - #1254

### LINKED ISSUE #1254: LCFS - Edit the other drop-down option in the FSE grid column "Level of equipment"
**Describe the task**
Edit the "Other" option in the FSE column dropdown titled "Level of Equipment" to read:
"Other- Additional information provided in notes field"

**Purpose**
To provide clearer guidance to users selecting the "Other" option in the Level of Equipment dropdown by specifying that additional information must be provided in the notes field. This improves clarity and ensures users include necessary details.

**Acceptance Criteria**

- [ ] Update the "Other" option in the Level of Equipment dropdown to display: "Other - Additional information provided in notes field."
- [ ]  Confirm that the updated option is displayed correctly in the dropdown list.
- [ ]  Verify that the update is applied consistently across all relevant pages and interfaces where the dropdown is used.
- [ ]  Test the functionality to ensure the updated option works as intended and does not disrupt existing data or workflows.

**Additional context**

### PR DESCRIPTION
**Pull request by hamed-valiollahi**
This PR updates the "Other" dropdown option in the FSE column titled "Level of Equipment" to clarify additional information should be provided in the notes field.

Closes #1254

### CODE REVIEW

**Review by dhaselhan — CHANGES_REQUESTED** [review]
Since we have already deployed production, I don't think seed data will run again. Do we need a migration as well?

**Comment by AlexZorkin** [comment]
Just echoing @dhaselhan's comment. Yes any data change in seeders that has already happened will need the seeder updated but also a migration to fix the live data.

**Comment by hamed-valiollahi** [comment]
Thank you, @dhaselhan and @AlexZorkin, for your feedback! I’ve made the changes.

**Review by dhaselhan — APPROVED** [review]
LGTM 👍

**Pull request merged**
